xiaomi:
  preprod:
    caps:
      platformName: "Android"
      automationName: "UiAutomator2"
      #appPackage: "com.abonesepeti.app.test"
      #appActivity: "com.abonesepeti.presentation.main.MainActivity"
      deviceName: "Xiaomi"
      platformVersion: "12"
      udid: "c2a1b4cc"
      app: "/home/livde/AboneSepeti/config/apk/abonesepeti-2.1.0-test3.apk"


    appium_lib:
      server_url: "http://0.0.0.0:4723"
      wait_timeout: 15
      wait_interval: 0.5
 
  prod:
    caps:
      platformName: "Android"
      automationName: "UiAutomator2"
      appPackage: "com.abonesepeti.app"
      appActivity: "com.abonesepeti.presentation.main.MainActivity"
      deviceName: "Xiaomi"
      platformVersion: "12"
      udid: "c2a1b4cc"
      app: config/apk/Abonesepeticanli.apk
    appium_lib:
      server_url: "http://0.0.0.0:4723"
      wait_timeout: 15
      wait_interval: 0.5

emulator:
  preprod:
    caps:
      platformName: "Android"
      automationName: "UiAutomator2"
      appPackage: "com.abonesepeti.app.test"
      appActivity: "com.abonesepeti.presentation.main.MainActivity"
      deviceName: "Medium_Phone_API_35"
      platformVersion: "13"
      avd: "Medium_Phone_API_35"
      autoGrantPermissions: true
      grantPermissions: true
      permissions: '{"com.abonesepeti.app": {"android.permission.POST_NOTIFICATIONS": "granted"}}'
      app: "/home/livde/AboneSepeti/config/apk/abonesepeti-2.1.0-test3.apk"
    appium_lib:
      server_url: "http://0.0.0.0:4723"
      wait_timeout: 15
      wait_interval: 0.5

  prod:
    caps:
      platformName: "Android"
      automationName: "UiAutomator2"
      appPackage: "com.abonesepeti.app"
      appActivity: "com.abonesepeti.presentation.main.MainActivity"
      deviceName: "Medium_Phone_API_35"
      platformVersion: "13"
      avd: "Medium_Phone_API_35"
      autoGrantPermissions: true
      grantPermissions: true
      permissions: '{"com.abonesepeti.app": {"android.permission.POST_NOTIFICATIONS": "granted"}}'
      app: config/apk/Abonesepeticanli.apk
    appium_lib:
      server_url: "http://0.0.0.0:4723"
      wait_timeout: 15
      wait_interval: 0.5
